### ISSUE TITLE
Support for version rocket 0.5.1

### ISSUE THREAD

**Issue by kontsaki** [GREsau/okapi#152]
Hello,

Is this planned? any ETA?

Do you need help?

The problem is with `rocket_db_pools` and latest `sqlx`. Previous SQLx versions have a CVE but `rocket_db_pools` version 0.2 which supports latest sqlx has a dependency to rocket version 0.5.1. Combined with `rocket_api`'s hard dependency to rocker version 0.5.0, there is no way to upgrade sqlx.

**Comment by ralpha** [comment]
Sorry for the late update. But just merged some MRs that bump the version.
After I have a look at the open issues and MRs I'll publish a new version to crates.io

If you to help you can test your project with the new version (strait from git).
```toml
[dependencies]
rocket_okapi = { git = "https://github.com/GREsau/okapi.git", features = [ ...whatever you need... ] }
```
Just make sure it compiles and works as intended. Should work fine as there are not many changes, but more changes might happen over the next days.
