### ISSUE TITLE
How to derive JsonSchema for Json<> structs

### ISSUE THREAD

**Issue by richardmarston** [GREsau/okapi#49]
I am trying to use okapi with a custom Responder for a Json<> wrapped struct. I am getting this error:

```bash
   Compiling openapi-responder v0.1.0 (/home/richard/small_test_projects/openapi_responder)
error[E0277]: the trait bound `rocket::serde::json::Json<Example>: JsonSchema` is not satisfied
  --> src/main.rs:20:12
   |
20 |     inner: Json<Example>,
   |            ^^^^^^^^^^^^^ the trait `JsonSchema` is not implemented for `rocket::serde::json::Json<Example>`
   |
   = note: required by `add_schema_as_property`
```

Here is my Cargo.toml:

```toml
[package]
name = "openapi-responder"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = [ "json" ] }
serde = { version = "1.0.64", features = ["derive"] }
serde_json = { version = "1.0.64" }
okapi = "0.6.0-alpha-1"
rocket_okapi = "0.7.0-alpha-1"
rocket_okapi_codegen = "0.7.0-alpha-1"
schemars = "^0.8"
```

Here is my main.rs:
```rust
#[macro_use]
extern crate rocket;
extern crate rocket_okapi;
use rocket_okapi::{openapi, routes_with_openapi, OpenApiError, response::OpenApiResponderInner, gen::OpenApiGenerator, util::add_schema_response};
use okapi::openapi3::Responses;

use rocket::serde::json::Json;
use serde::{Deserialize, Serialize};
use schemars::JsonSchema;

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct Example {
    error: String,
}

#[derive(Responder, JsonSchema)]
#[response(content_type = "json", status=200)]
pub struct ExampleResponse {
    inner: Json<Example>,
}

#[openapi]
#[get("/example_response", format="application/json")]
pub async fn get_example_response() -> ExampleResponse {
    ExampleResponse { inner: Json(Example { error: "hi".to_owned() } ) }
}

impl OpenApiResponderInner for ExampleResponse {
    fn responses(gen: &mut OpenApiGenerator) -> Result<Responses, OpenApiError>{
        let mut responses = Responses::default();
        let schema = gen.json_schema::<Json<Example>>();
        add_schema_response(&mut responses, 200, "application/json", schema)?;
        Ok(responses)
    }
}

#[rocket::main]
#[doc = "The main entry point for Rocket" ]
async fn main() -> Result <(), rocket::Error> {
    rocket::build()
        .mount("/", routes_with_openapi![get_example_response])
        .launch()
        .await
}
```

I don't understand how I can generate the schema for a Json struct. I can't use the derive(JsonSchema) attribute because it's not a struct, enum or union.
