### ISSUE TITLE
Compatibility with Rocket 0.5rc2

### ISSUE THREAD

**Issue by svenstaro** [GREsau/okapi#88]
Just released Rocket 0.5rc2 seems incompatible with rocket-okapi right now.

**Comment by ralpha** [comment]
You are all quick. This issue was opened an hour after the release :smile: 
I'll try to get an update ready soon.
@ThouCheese already made PR: https://github.com/GREsau/okapi/pull/89. But it looks like [Schemars might need an update first](https://github.com/GREsau/schemars/pull/138).
So will so how quickly that can happen.

Might also do some general maintenance before release as well, so some other issues are fixed too. (help is always welcome, just look though the open issues and see if you can help out with any/some of them)

**Comment by svenstaro** [comment]
> You are all quick.

Well, _gotta go fast_. :hedgehog::sunglasses:

**Comment by NCrashed** [comment]
Just to note, that the issue affects me too. Cargo treats the rc.2 as minor bump and breaks you build every time you updates you lock file.

**Comment by olback** [comment]
> Just to note, that the issue affects me too. Cargo treats the rc.2 as minor bump and breaks you build every time you updates you lock file.

You can work around this for now by specifying exactly what version you want `rocket = "=0.5.0-rc.1"`. Notice the equals inside the quote.

**Comment by hardliner66** [comment]
> > Just to note, that the issue affects me too. Cargo treats the rc.2 as minor bump and breaks you build every time you updates you lock file.
> 
> You can work around this for now by specifying exactly what version you want `rocket = "=0.5.0-rc.1"`. Notice the equals inside the quote.

Except that it doesn't work. The internal dependency on rocket_http resolves to 0.5.0-rc.2 because it is seen as a minor bump.

**Comment by olback** [comment]
> > > Just to note, that the issue affects me too. Cargo treats the rc.2 as minor bump and breaks you build every time you updates you lock file.
> > 
> > 
> > You can work around this for now by specifying exactly what version you want `rocket = "=0.5.0-rc.1"`. Notice the equals inside the quote.
> 
> Except that it doesn't work. The internal dependency on rocket_http resolves to 0.5.0-rc.2 because it is seen as a minor bump.

Yup, that's correct. I just ran `cargo update` and it broke.

**Comment by hardliner66** [comment]
Instead of pinning rocket, which doesn't work, you could just use the pull request to fix this issue instead.
Something like this: `rocket_okapi = { git = "https://github.com/ThouCheese/okapi", branch = "feat/rocket0.5-rc.2", features = ["rapidoc", "swagger"] }`

**Comment by Glitchy-Tozier** [comment]
In case someone finds it helpful, this is how i solved the problem: I precisely defined what versions I wanted for each rocket-dependency I used. `version = "=..."` instead of `version = "..."`

```toml
# Precise imports required to prevent automatic updating to `...-rc.2`
rocket = { version = "=0.5.0-rc.1", features = ["json"] }
rocket_codegen = "=0.5.0-rc.1"
rocket_http = "=0.5.0-rc.1"
rocket_sync_db_pools_codegen = "=0.1.0-rc.1"


[dependencies.rocket_dyn_templates]
features = ["tera"]
version = "=0.1.0-rc.1"

[dependencies.rocket_sync_db_pools]
default-features = false
features = ["diesel_postgres_pool"]
version = "=0.1.0-rc.1"
```
